packages:
  - 'artifacts/*'
  - 'lib/*'
  - 'scripts'

overrides:
  "@clerk/react": "^5.54.0"
  "@clerk/shared": "^3.48.0"
  "@clerk/themes": "^2.4.57"

catalog:
  # Clerk Fix
  "@clerk/react": "^5.54.0"
  "@clerk/shared": "^3.48.0"
  "@clerk/themes": "^2.4.57"
  
  # Build Tools (Amma kan sitti dhufe)
  "tsx": "^4.19.2"
  "zod": "^3.23.3"
  "typescript": "^5.9.3"
  "vite": "^5.4.11"
  "@vitejs/plugin-react": "^4.3.4"
  "@types/node": "^22.14.0"
  "@tanstack/react-query": "^5.66.0"
  "prettier": "^3.3.3"
